# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bq-gpt',
                'doc_host': 'https://hamelsmu.github.io',
                'git_url': 'https://github.com/hamelsmu/bq-gpt',
                'lib_path': 'bq_gpt'},
  'syms': {'bq_gpt.core': {}}}
